devices
Fushicai USBTV007 grabbers (1b71:3002) return very dark images in Ubuntu 16.04 and later due to bug fix of v4l2 controls ([https://github.com/torvalds/linux/commit/c53a846c48f21c909102677c127ece94b1247668](url)). Brightness and contrast values of the usbtv kernel module can be controlled by v4l2-ctl from the v4l-utils package.
=> v4l2 control of usbtv kernel module.

RMS/StartCapture.py
This changes RMS start process: if it's not capture time, look for partially-processed folders then call Reprocess code for all of them, except if FTPdetect file is found in a folder with same name on archived directory.  The results are added to the upload queue.
Please note the FTPdetect check was not fully tested yet!
=> Reprocess on crash

RMS/Formats/AsgardEv.py
- time, cx, cy, th, phi fields now have 6 digits of precision instead
of 3 to address rounding errors
=> Change ASGARD format to match upstream UWO version

RMS/BufferedCapture.py
This prints estimated FPS when report_dropped_frames is enabled, to help debug frame grabbing issues
=> log estimated FPS when report_dropped_frames is enabled

RMS/StartCapture.py, iStream/iStream.py, iStream/iStream.sh
istream.sh output used to go to stdout only, getting lost across reboots and when terminal buffer replaces it.
Ths patch makes use of RMS standard log mechanism to preserve log of execution by creating its own file with prefix iStream_log_ in ~/RMS_data/logs/.
Also, makes use of RMS ExternalScript lock file mechanism, respecting user-configurable option "reboot_after_processing".
=> iStream- improve logging and modify reboot/lock mechanism

iStream/iStream.sh
ffmpeg is being seem stuck using 100% of a CPU for +12 hours and
affecting next capture night, probably due to a bug in ffmpeg.
This change works around it making sure timelapse video generation
have a hard stop 120 seconds before next night session starts.
=> iStream: add time limit for generating timelapses

Utils/CheckNight.py
The keys returned from `cv.waitkey()` seem to be platform dependent. This adds support for my platform; I think this is fully backward compatible.
=> added key codes for macos to checknight

Scripts/RMS_StartCapture.sh
This should get rid of warnings like `mkdir: cannot create directory ‘~/RMS_data/logs/’: No such file or directory` and `mkdir: cannot create directory ‘/home/pi/RMS_data/logs/’: File exists`.
=> Get rid of warning

Scripts/RMS_SetCameraParams.ps1, Scripts/RMS_SetCameraParams.sh
Tested in the following scenarios:
1) Script run from PC. Camera plugged into PC, PC ethernet port set to 192.168.1.x range as per video by Denis Vida.
2) Script run from Pi. Camera plugged into router. Home network range 192.168.1.x 
NOT tested and not expected to work yet
3) script run from Pi, camera plugged into Pi.
=> Improvements to script to set camera parameters

.gitmodules, README.md, Utils/CameraControl.py, requirements.txt, setup.py
Drop git module and pin python-dvr to the latest commit.
After https://github.com/NeiroNx/python-dvr/pull/24 was merged,
python-dvr can be pip installed directly from git.
Note that git refs do not work for setuptools install_requires,
so pip install -r requirements.txt is required to be executed before
python setup.py install !
=> [WIP] Use python-dvr directly

RMS/Formats/UFOOrbit.py
When the event time was being written to the file, if seconds + microseconds > 59.99 it was being rounded up to 60, 60 is an invalid value for the seconds field of a datetime, and an invalid date/time was being exported
For example 59.9991 seconds was rounded up to 60,.00 and so the following was written to the CSV file
2021, 4, 11, 20, 57, 60.0
when it should have been
2021, 4, 11, 20, 58, 0.0
(This was causing cmn_BinViewer to abort on certain datasets. )
=> Small bug in RMS2UFO

Utils/SkyFit2.py
Silence warnings like implicit convertion to int, and the one bellow:
/mnt/c/Users/thund/source/RMS/Utils/SkyFit2.py:1335: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
filter_indices_mask = np.zeros(len(cat_stars_xy), dtype=np.bool)
=> SkyFit2: silence deprecation warnings on python 3.8

Scripts/RMS_Update.sh, Utils/CameraControl.py, setup.py
As per previous pull request by apevec, its possible to use dvrip as a standard module rather than as a submodule. While testing this i realised that the syntax has changed slightly, and as noted by apevec, its necessary to call pip install -r requirements.txt before running setup,py so that the modules are all installed as expected. This pull request addresses these points.
I've tested the changes on both my Pi3/Jessie/Py2.7 and Pi4/buster/Py3.7 without any issues.  As expected, with python 2.7 the dvrip module was not installed. 
ps also fixed some typos in the help info for SetAutoReboot
=> Updates to make use of dvrip directly

Utils/FFtoFrames.py, Utils/GenerateMP4s.py
The timestamps in GenerateMP4s (which since #63 update every second) still refer to the beginning of the FF-file. This fixes that bug.
I think @markmac99 [used](https://github.com/CroatianMeteorNetwork/RMS/commit/bd8f2e0cc5f7b35ed909c33aaa700fe2e0e931ff#diff-10fc682193c6d4db0d6b9e90e011cd3f37e749215b3b2838aada1af737e5132dL163) `i-first_frame` in the call to `saveFrame` to make the output JPGs start counting at 0 to make the input to ffmpeg easier. There are two problems with this:
- It's inconsistent with the interlaced variants
- It messes up the timestamps
Since both ffmpeg and avconv support specifying the number of the first frame, it's also not necessary.
=> Fix timestamps in GenerateMP4s

Utils/SetCameraAddress.py
Foolish error in setcameraaddress - it doesn't allow for IPaddresses either of whose middle two digits could be zero...
=> Bugfix in setcameraddress

Utils/FRbinViewer.py
Enhancement to FRbinViewer to create an mp4 of the data.
FRbinViewer can already be used to export one or more FR files as a set of still images in jpg, bmp or png format. I often use these to create a more detailed video of fireballs than can be generated from the FF file.
With this enhancement, if the selected export type is "mp4" then FRbinViewer will automatically create an mp4 video rather than stills. This uses the same essential logic as GenerateMP4s.   There is no change in the exposed interface, except that passing in "-f mp4" will now result in a video rather than an error! 
Note: FRbinViewer operates on a whole folder and some FR files may contain more than one 'line', so multiple MP4s will usually be created. To avoid creating unwanted videos of clouds and aircraft, the user …
=> Enhancement to FRbinViewer

Scripts/GenerateDesktopLinks.sh
Pete Eschman reported that the desktop link for BinViewer doesn't work. Confirmed and fixed - needs to run Scripts/CMNbinViewer_env.sh so that the python virtualenv is activated.
=> Bugfix - desktop link to Binviewer doesn't work

RMS/Formats/FrameInterface.py, Utils/SkyFit2.py
I have these two changes locally for a long time, just realized that.
One silences a deprecation warning, making sure the value is integer.
The second one avoids crashing when reading a broken video recorded by UFO Capture, it continues gracefully instead.
(I tried to create the pull request against "dev" branch but looks like it's out of sync with master)
=> Video read error handling

RMS/Misc.py
This fixes ping on Windows 10 using  Python 3.9.1. The method subprocess.call didn't like "-n 1" (two parameters) as a single element in the array and the IP address is not being passed to ping command:
>>> import subprocess
>>> subprocess.call(["ping", "-n 1", "192.168.42.10"])
O endereço IP deve ser especificado.
1
=> Fix ping on Windows

RMS/ConfigReader.py, RMS/DeleteOldObservations.py, iStream/iStream.sh
Add functionality to clear down the RMS logs. 
New parameter in config file "logdays_to_keep". 
If new parameter missing, default 30 days is used. 
Only clears down files matching pattern "log*.log*"
=> Clear down RMS logs

iStream/iStream.py
Fix bug in test for on linux. Import of os within the function was masking the global import, so that os.path.join on line 17 was treated as an undeclared variable and iStream.py was then crashing. Removing the second import fixed the problem. NB: this code isn't in master yet. 
Also tidied up a bit of formatting. 
Error message was only visible onscreen and was:
File "/home/pi/source/RMS/iStream/iStream.py", line 17, in rmsExternal
lockfile = os.path.join(config.data_dir, config.reboot_lock_file)
UnboundLocalError: local variable 'os' referenced before assignment
=> istream crashing in test for whether on Linux or Pi.

Utils/FRbinViewer.py
Changed `FRbinViewer.py` so that it combines shows all lines in a given _FR*.bin_ file as a single video. Users can still instruct viewer to use old behavior by using `-s` or `--split` argument which is probably useful when using the viewer to generate video files.
=> FRbinVIewer change

Utils/TrackStack.py
When track-stacking multiple cameras or multiple nights, the initial canvas may be too small, leading to cropping of the final image. This arises because to estimate the size required, the code calculates the angular separations of each frame from the refernce. Normally, this will be at a maximum with the latest or earliest image. However, in the scenarios above, the angular separation does not behave in the same way, leading to canvases that are too small. 
This fix adds a --scalefactor parameter that scales the canvas up by the specified amount. This increases the amount of memory required by scalefactor squared, which could cause issues on low-memory machines. Hence its an optional parameter and the default is to keep the original size. 
Example attached showing the cropped and …
=> fix to trackstack bug #70 raised by D Rollinson

Utils/DrawConstellations.py, Utils/TrackStack.py
This should improve the drawing of constellations of wide-field trackstacks. Previously, a field of view of 90 degrees was hardcoded to prevent wrapping around the sphere.
I hope @g7gpr can test this.
=> Use computed field of view for constellations

requirements.txt
Fix deprecated np.bool error on newer numpy version: 
(Try to open the screenshot image on the new tab if the message is too small, sorry!)
Steps-to-reproduce: 
1. Install deps from requirements.txt
2. Install latest numpy version (e.g. v1.24.0)
3. Install latest imreg_dft (v2.0.0) from pypi
4. Try to reprocess the pickle
The latest commit on the source already has a fix for the deprecated np.bool, but not published to pypi yet.
=> fix: bump imreg_dft to remove deprecated np.bool

RMS/QueuedPool.py
When running processing after capture, worker_timeout is generally not an integer, as it includes the capture duration. This change converts it to an int for logging.
=> Convert worker_timeout to int for logging

RMS/EventMonitor.py
Some stations do not reboot each day, so start_time must be recalculated on each iteration
=> Update start_time for systems which do not reboot each day.

RMS/EventMonitor.py
https://github.com/CroatianMeteorNetwork/RMS/issues/213
Report of a crash of EventMonitor following parsing a zero length .config file found in a CapturedFiles directory. This fix uses the station .config file in this event.
=> Handle zero length .config file

RMS/EventMonitor.py
This fix relates to issue #233.
Includes code to retrieve the platepar from the RMS root directory, often "~/source/RMS".
This is needed because the platepar file is not copied to the CapturedFiles directory until the end of capture.
=> Fix for platepar retrieval whilst capture is in progress

RMS/DeleteOldObservations.py
lat and long passed to ephem() must either be radians as a float, or degrees as a string eg 0.91 or "51.8".  
However we're currently passing the value in degrees as a float which is then interpreted as a value in radians. Ephem normalises it  to the range -pi/2 to pi/2 so for example 51.8 converts to 1.5345, which is equal to 87.9 degrees north.  Not the desired latitude ! 
The subsequent call to work out sunrise is then failing for half the year since the sun never rises at this latitude. As a result, deleteOldObservations is silently failing and no space is freed. 
This patch fixes it by converting the lat/long values to strings, as we do elsewhere in the code. An alternative would be to convert to radians, but its simpler and more consistent with other code to use str()
=> Fix bug in deleteOldObservations

RMS/Routines/CustomPyqtgraphClasses.py
auto data type retyping from float to int is not supported by python3.10+
=> python3.10+ compatibility fix

RMS/StartCapture.py
This PR addresses the problem described in issue #249, where `dropped_frames` was always reported as zero due to its assignment occurring after `bc.stopCapture()` in `startCapture.py`. The proposed change ensures that the correct number of dropped frames is reported in the logs.
Changes made:
- Moved the assignment of `dropped_frames` from after `bc.stopCapture()` to just before it. This change ensures that `dropped_frames` is accurately reported before the capture stops.
Fixes #249
=> Fix Dropped Frames Count Reporting in StartCapture

RMS/DeleteOldObservations.py
Bug reported by Rick Hewett
Tested on UK0006 by setting the config variables to zero, then commenting them out to simulate an unupdated file, then setting them to 20 to simulate a manual override
```
(vRMS) pi@uk0006:~/source/RMS $ egrep "bz2|arch_dirs_to_keep" .config
; how many ArchivedFiles and bz2 files to keep
arch_dirs_to_keep: 0
bz2_files_to_keep: 0
(vRMS) pi@uk0006:~/source/RMS $ python -m RMS.DeleteOldObservations
Loading config file: /home/pi/source/RMS/.config
2024/01/20 14:28:29-INFO-DeleteOldObservations-line:447 - deleting obs from /home/pi/RMS_data
2024/01/20 14:28:29-INFO-DeleteOldObservations-line:230 - clearing down log files
2024/01/20 14:28:29-INFO-DeleteOldObservations-line:234 - clearing down old data from ArchivedFiles
2024/01/20 …
```
=> bugfix for condition where bz and arc to keep are both zero

Utils/SkyFit2.py
I've amended skyfit2 to include the FF filename in the state file. 
Now, if you run SkyFit2 on a folder containing more than one FF file, you can either
a) use the folder as before, move between FF files and then work on the one you want to use; or
b) load the state file. In this case, the right FF file is automatically loaded for further analysis
I've done some testing with fireballs without any issues, but would appreciate further review / input.
Closes #262
=> small change to SkyFit2 to save the FF name in the state file.

RMS/Reprocess.py, Utils/FluxAuto.py, Utils/FluxBatch.py, Utils/PlotTimeIntervals.py, Utils/SkyFit2.py, requirements.txt
This PR introduces `PlotTimeIntervals.py`, a utility that generates a plot displaying the intervals between FF file timestamps. It also assigns a score ranging from 0 to 1000, with higher scores indicating less variability in the timestamps.
During reprocessing, this utility is invoked on the `night_dir`, logging a score and incorporating it into the plot's filename. If insufficient intervals are present to calculate a meaningful score, none is returned. The plot and score aim to function as diagnostic tools for identifying timestamping and dropped frame issues.
The utility uses Pandas to find outliers, and `pandas` has been added to requirements.txt. If this is a pain point, the utility can be redisigned without this feature.
The scoring is somewhat arbritary and designed to offer what …
=> Plot, score, and log timestamp intervals for analysis

Utils/FRbinViewer.py
This is a fix for cases when we have several tracked meteors on on same fits file and identification was wrong as it took first meteor from list
Implemented solution:
Usage of meteor start and end time to compare with start and time of bin video (calculated by frame number)
If meteor time range inside video time range - this is the best candidate.
Also during testing found that video could start with small lag (1 or 2 frames later) .
To fix it was introduced time offset for 100mls before and after video start (if fps is 25 then 1 frame ~40mls )
It fixed issue on my test suite.
What was not tested:
As  I can see bin file could be multi lines and I don't have such example and don't know when such file could be created, also exists option '--split' which also could affect calculation.
This …
=> Add meteor to end of bin video - fix for multi meteors on same fits file

RMS/Compression.py, RMS/Formats/FFfile.py, RMS/Formats/FFfits.py
This PR is related to PR #257. Because PR #257 improves frame timestamping and makes microseconds significant, this PR preserves the microseconds information instead of rounding to milliseconds. Due to compatibility concerns with downstream processes, the FF filename structure remains unchanged, still displaying only milliseconds. To retain microseconds, a new **EXPSTART** header field is added to store the datetime string with microseconds:
```
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                    8 / array data type                                
NAXIS   =                    0 / number of array dimensions                     
EXTEND  =                    T                                                  
NROWS   = …
```
=> Add support for microseconds in FS filenames and FF headers

Utils/ShowLiveStream.py
This PR incorporates media_backend config setting support for v4l2. ShowLiveStream will continue to use OpenCV, even if media_backend is set to gst, for the sake of simplicity.
=> Fix v4l2 support in ShowLiveStream

RMS/BufferedCapture.py, RMS/Compression.py, RMS/StartCapture.py
In a multicam setup, a ‘Bus Error (Core Dumped)’ can occur during the reinitialization of frame buffers in subsequent nightly runs. This issue arises because the frame buffers, which are utilized by `StartCapture`, `Compressor`, and `BufferedCapture`, are only being freed in `StartCapture` upon exit. This PR addresses the problem by ensuring that the frame buffers are properly freed in all three classes upon their respective exits.
=> Ensure all shared buffers are properly freed

RMS/BufferedCapture.py
This PR addresses issue #299 by only adding a trailing slash to URLs ending with '.sdp' instead of always adding a trailing slash if one is missing.
=> Only add trailing slash to URL ending with '.sdp'

RMS/EventMonitor.py
When CapturedFiles directory contains files, which are named in a similar way to an observation directory, and an event is created which references a time which matches the naming of the files, files get returned from getDirectoryList, rather than just directories, as described in issue #304  
This pull request removes any files, so that only directories are returned.
=> Prevent getDirectoryList from returning files

.config, RMS/BufferedCapture.py, RMS/ConfigReader.py
Added a configuration parameter `protocol` to `.config` that can be set to 'udp' or 'tcp'. It defaults to TCP: If not set to 'udp' the code uses TCP. I hope this will solve some disconnect issues, especially on Multicam setups.
One minor issue when running UDP is that GStreamer might issue a warning message about memory size:
```
warning: Could not create a buffer of requested 524288 bytes (Operation not permitted). Need net.admin privilege?
0:00:00.107728875 32187     0x24a0d6a0 WARN                  udpsrc gstudpsrc.c:1647:gst_udpsrc_open:<udpsrc0> have udp buffer of 212992 bytes while 524288 were requested
```
The stream will proceed fine despite the warning, but increasing the system’s maximum UDP buffer size by modifying the /etc/sysctl.conf file solves the issue. Adding the …
=> Add configurable Transport Protocol: UDP or TCP

RMS/ExtractStars.py
Addresses issue #326 by using `extractStarsFF` function in `QueuedPool` instead of `extractStars`.
=> Use extractStarsFF in QueuedPool

RMS/ConfigReader.py
Issue #319 notes that detector can fail with the following error
```
2024/07/31 18:45:27-INFO-QueuedPool-line:204 - Traceback (most recent call last):
File "/home/au0004/source/RMS/RMS/QueuedPool.py", line 356, in _workerFunc
result = func(*all_args, **self.func_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/au0004/source/RMS/RMS/DetectStarsAndMeteors.py", line 98, in detectStarsAndMeteors
meteor_list = detectMeteors(img_handle, config, flat_struct=flat_struct, dark=dark, mask=mask)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/au0004/source/RMS/RMS/Detection.py", line 1107, in detectMeteors
line_list = getLines(img_handle, config.k1_det, config.j1_det, config.time_slide, config.time_window_size, …
```
=> Fix for kht_binary_search

requirements.txt
https://pypi.org/project/tflite-runtime/
=> Update requirements.txt as tflite-runtime 2.14.0 now support python 3.11

RMS/Astrometry/CyFunctions.pyx, RMS/UploadManager.py, Utils/AuditConfig.py
This PR addresses issue #342 by replacing Python 3-specific f-strings with .format() and substituting the FileNotFoundError exception (which is not Python 2 compatible) with IOError.
=> Fix Python 2 Compatibility for Issue #342

RMS/BufferedCapture.py
This PR introduces additional improvements to the GStreamer pipeline state management process, particularly focusing on enhancing the robustness of transitioning the pipeline to the `PLAYING` state. These changes aim to reduce the risk of **indefinite blocking** that were still occasionally occurring, especially in scenarios where stations have unreliable network connections leading to frequent disconnects. The updates also optimize timeouts during reconnects to minimize the loss of observation time.
1. **Incremental Timeout for State Transitions**:
- Implemented an increasing timeout strategy for the `get_state()` function when transitioning the pipeline to the `PLAYING` state. The timeout now grows with each retry attempt, starting at 5 seconds and increasing by 5 seconds for each …
=> Further Improve Pipeline State Management with Enhanced Retry Logic

Scripts/RMS_Update.sh
`RMS_Update.sh` checks for the presence of key libraries and attempts to install them if missing. Currently, if the user lacks passwordless sudo privileges, the installation is skipped with a brief note suggesting granting such privileges. However, granting passwordless sudo access poses security risks.
- `RMS_Update.sh` skips library installation if the user doesn't have passwordless sudo privileges.
- It suggests granting passwordless sudo privileges and skips installation.
- The message disappears quickly and is easy to miss.
This PR updates `RMS_Update.sh` to implement a more secure and user-friendly approach:
1. Check for missing libraries.
2. If libraries are missing:
a. Attempt installation without a password.
b. If a password is required, prompt the user.
c. Allow 30 seconds for …
=> Prompt for Password if needed when Installing Missing Libraries

RMS/Reprocess.py
Handle the case when plotFFTimeIntervals() returns None which arises if the FS archive bz2 file is not available.
=> Update Reprocess.py to avoid error if jitter_quality unavailable

Utils/AuditConfig.py
Allow auditconfig to run on Py2.7
=> Py2.7 remove non-ascii and choose ConfigParser

Scripts/RMS_Update.sh
I'm hoping this addresses #349. In any case, this PR adds a cleanup of all *.so files in the source dir when RMS_update is run.
=> Cleanup for *.so files in the repository folder

RMS/ConfigReader.py, RMS/Formats/FTPdetectinfo.py, RMS/Misc.py, RMS/UploadManager.py, Utils/AuditConfig.py, Utils/FluxBatch.py, Utils/PlotTimeIntervals.py, Utils/TimestampRMSVideos.py
Addresses issue #344 by mapping FileNotFoundError to IOError if in Python 2.
The PR also reverse some premature changes where FileNotFoundError were changed to IOError.
=> Map FileNotFoundError to IOError if in Python 2

RMS/ConfigReader.py, RMS/Misc.py, Utils/SkyFit2.py
Optimize RMS module location without full import (Python 2/3 compatible)
Changes
- Replace direct `import RMS` with version-specific module location methods
- Use `importlib.util.find_spec()` for Python 3.x
- Use `pkgutil.get_loader()` for Python 2.7 (with deprecation note)
- Determine RMS root directory without importing the entire module
Benefits
1. **Memory Efficiency**: Avoids loading the entire RMS module into memory when only the path is needed
2. **Performance**: Faster initialization as it skips full module import
Implementation
```python
if sys.version_info[0] == 3:
import importlib.util
else:
import pkgutil
...
if sys.version_info[0] == 3:
rms_spec = importlib.util.find_spec('RMS')
if rms_spec is None or rms_spec.origin is None:
raise ImportError("RMS module not found.") …
```
=> Get the path to the RMS root directory without importing the whole codebase

RMS/Reprocess.py
This PR is in response to issue #399, and removes the unwanted space character from the Observation Summary log entry, also adding a title.
I'll leave this as draft until I have tested on a few of my own stations.
=> Remove unwanted space from Observation Summary log

RMS/Formats/ObservationSummary.py
Iss #389 requests that staionID is added to the observation summary report txt and json files. This PR adds that feature. 
```
Summary as colon delimited text
camera_fov_h                    : 53.68 
camera_fov_v                    : 29.972716 
camera_information              : Error 
camera_lens                     : 6mm 
camera_pointing_alt             : 44.43 degrees 
camera_pointing_az              : 260.28 degrees 
capture_duration_from_fits      : 42986.413 
captured_directories            : 5 
commit_date                     : 20240829_232717 
commit_hash                     : 0ca5395172d94472da06235ec4cd40cb03209e0e 
duration                        : 100 
fits_file_shortfall             : 10 
fits_file_shortfall_as_time     : 0:01:42.400000 
fits_files_from_duration        : …
```
=> Add stationID to observation summary

.config
These support quota management by disc use and deleting captured directories by count.
=> Additions to config file

RMS/Pickling.py
Addresses #403 by simply adding pickle.UnpicklingError to the list of checked errors.
=> Fix raising an unpickling error during reprocessing

RMS/Formats/ObservationSummary.py
Issue #411 notes that at least one station has been operating without valid time sync. This pr includes time sync status into the observation summary report, and a very approximate estimation of error that could be used to recover data at the server.
=> Report on time sync status

.config
Address issue #414. This enables weblog in the default config file.
=> Correct default config value for weblog

Utils/FOVKML.py
This PR updates the storage format for the FOV slice area height in both the KML file and the filename. The height is now stored as a decimal (rounded to 3 decimal places), rather than as an integer.
=> save kml files with decimal area_ht in filename

RMS/ConfigReader.py
In RMS/ConfigReader.py, Changed            
[1161] print("WARNING! The png_compression must be between 0 and 9. It has been reset to 90!")
to
[1161] print("WARNING! The png_compression must be between 0 and 9. It has been reset to 3!")
=> updated ConfigReader warning for png compression

RMS/StartCapture.py
Updates RMS/StartCapture.py to not produce an observation summary when using a video file (Resolves #417 )
=> Disable observation summary report creation when given video file

.config, RMS/ConfigReader.py, Utils/AuditConfig.py
=> Cleanup config options

.config, RMS/ConfigReader.py, RMS/Logger.py
This PR enhances logging capabilities with the following changes:
1. Enables logging of stderr messages.
2. Adds support for logging GStreamer messages when available.
3. Introduces a new configuration option to optionally log stdout messages (defaults to False)
These improvements are particularly useful for debugging, especially when capturing messages that are not explicitly logged through the main logging system.
The new config option `log_stdout` allows operators to include additional console output in the log file, providing more context when troubleshooting issues.
=> Log stderr, GStreamer, and optionally stdout messages

RMS/Logger.py
Reduce logging verbosity when GStreamer cannot be imported. This PR prevent logging GST imported status at logger initialization and remove some f-strings.
=> Don't log GST imported status at logger initialization

Scripts/RMS_SetCameraParams.sh, Utils/CameraControl.py
This PR adds the following settings to `RMS_SetCameraParams.sh`:
```
python -m Utils.CameraControl SetParam General VideoFormat PAL
python -m Utils.CameraControl SetParam Camera ClearFog enable 0
python -m Utils.CameraControl SetParam Camera ClearFog level 50
python -m Utils.CameraControl SetParam Camera BroadTrends AutoGain 0
python -m Utils.CameraControl SetParam Camera BroadTrends Gain 50
```
Setting VideoFormat to PAL ensures that the camera is not accidentally set to NTSC, which would affect the evenness of the frame rate.
**ClearFog** and **BroadTrends** are set to their default values in case they were changed to other settings for day observation. Setting **BroadTrends AutoGain** to 0 allows preservation of highlights during day observation.
The PR also changes the name and format …
=> Add support for VideoFormat, ClearFog, and BroadTrends Camera Settings

RMS/Astrometry/CyFunctions.pyxbld, RMS/CompressionCy.pyxbld, RMS/Routines/Grouping3Dcy.pyxbld, RMS/Routines/MorphCy.pyxbld
Currently, RMS can only function when the working directory is the RMS root directory because the `.config` path is defined relative to the working directory in the .pyxbld files. This is inconvenient when, for instance, we want to use RMS functions in other projects. This PR defines the `.config' path relative to the RMS root directory regardless of the actual working directory path.
=> Define .config Path Relative to RMS Root

RMS/Formats/ObservationSummary.py
Get RMS repo info no matter what working directory we're in.
=> Fix repo path in Observation Summary

RMS/Reprocess.py
This pull request adds a FOV check for the platepar in the `Reprocess.py` file. The check ensures that the FOV in the platepar is within a factor of two of the FOV in the config file. If the FOV ratio is smaller than 0.5 or greater than 2, the platepar is not used. This check helps to ensure that the platepar and config file are compatible before using the platepar for further processing.
Example of when this is needed: https://globalmeteornetwork.org/weblog/US/US003F/US003F_20240924_021434_064110_detected/
=> Add FOV check for platepar

RMS/ConfigReader.py, RMS/MLFilter.py
If tflite-runtime is not present, this PR silences TensorFlow nuisance messages about GPU not being configured.
=> Silence full TensorFlow nuisance messages

RMS/BufferedCapture.py, RMS/Misc.py
Currently, camera passwords are logged in plain text. Since logs are sometimes shared for troubleshooting, operators may unwittingly expose their passwords. Although the majority of cameras use default passwords, some have non-default passwords that should not be logged. This PR obfuscates camera passwords in the logged URL if they differ from the default password.
=> Obfuscate passwords in log

Scripts/UpdateBuffers.sh
GStreamer is reporting UDP buffer allocation warnings in the logs when `protocol: udp` is selected in `.config` :
```
GStreamer: udpsrc: warning: Could not create a buffer of requested 524288 bytes
```
This occurs because GStreamer's UDP source is requesting 512KB buffers while system defaults are often lower. Even with the warning, capture usually proceeds normally, however the smaller buffer may cause issues under high work load. 
Added a script `UpdateBuffers.sh` that:
- Checks current UDP buffer sizes
- Warns if buffers are below recommended sizes (512KB minimum, 1MB recommended)
- Offers to increase buffer sizes if needed
- Creates a backup of original settings
- Shows before/after comparison
```bash
sudo ./Scripts/UpdateBuffers.sh
```
- Each camera's UDP source requests a 512KB …
=> Increase UDP Buffer Size Configuration Script

RMS/BufferedCapture.py, RMS/RawFrameSave.py
The framestamps.json file would start counting from 0 after a reboot. This fixes it by initializing the starting raw frame value from an existing framestamp file for the current day, if it exists.
=> continue framestamps.json for current day after reboot

RMS/Reprocess.py, Utils/GenerateTimelapse.py
- refactored generateTimelapseFromFrames - no need to pass in framestamps.json files now.
- The timestamps in the raw frames timelapse are now formatted like the FF file timelapse
=> refactored GenerateTimelapse.py

RMS/StartCapture.py
Rearranged the check for 'config.auto_reprocess' so that it is run in case 'config.continuous_capture = True' .
This affects functionality of continuous_capture as capture may not start running immediately if incomplete files exist.
(Please review)
=> always check for auto-reprocessing option

RMS/CaptureModeSwitcher.py, RMS/StartCapture.py
In case the capture switcher thread fails (most likely camera connection issues), then capture is restarted with continuous capture disabled.
=> added health check for capture switcher thread

RMS/RawFrameSave.py
In case the date switches during raw frame saving, the frame counter must be reset for the next day. This PR corrects the logic to handle this by accounting for an edge case with the first timestamp of a block.
=> corrected date-switching in RawFrameSave.py

RMS/CaptureDuration.py, RMS/CaptureModeSwitcher.py, RMS/StartCapture.py
- Account for AlwaysUp and NeverUp errors in CaptureModeSwitcher.
- Automatically set continuous capture to false when a fixed duration or video file is given.
=> continuous capture fixes

RMS/DeleteOldObservations.py
Currently, during purging, the process hangs if deletion does not decrease the folder count below the determined threshold. This PR exits the deletion loops if the folder count doesn't decrease. 
Deletion may not occur for a variety of reasons, including the non-deletion of unprocessed frame files.
=> Exit deletion loops if folder count doesn't decrease on deletion attempts

RMS/CaptureModeSwitcher.py
Simultaneous camera mode switching on MCL can be unstable. This PR uses the config `capture_wait_seconds` to stagger the camera switching. On initial run, the mode switching is not delayed as capture_wait_seconds already delays start capture.
=> Stagger camera mode switching

RMS/StartCapture.py
This PR address issue #482, though the underlying mechanism is unclear to me. The PR simply adds a log entry when CTRL-C is pressed. Surprisingly, this seemingly restores the functionality of CTRL-C.
=> Add log entry to prevent ctrl-c failure

.config, RMS/ConfigReader.py, RMS/DeleteOldObservations.py
This PR is for clarity within the DeleteOldObservations code:
- changes the naming convention of frame_dirs_to_keep to frame_days_to_keep
- changes the naming convention of functions getRawDirs / deleteRawDirs to getRawItems / deleteRawItems
- improved language in comments and docstrings of the above functions
- in FramesFiles, each day consists of three processed files (frames archive, timelapse and frametime json). The code now automatically handles the frame_days_to_keep config option against this detail gracefully
=> Improved raw items (videos and frames) deletion

RMS/StartCapture.py
For issue #495 
The block including start_time checking is skipped in case of continuous capture, allowing retry for a full 4 hours before capture start.
Previously, as start_time is set to True for continuous capture, reboot retry won't occur if a lock_file is present and
`waiting_time = start_time - time_now`
will throw an error.
=> continuous capture retry with lock file check

RMS/BufferedCapture.py
This PR refines the frame-saving logic so RMS dynamically handles color vs. grayscale in both the GStreamer and OpenCV paths. On every save_frames_interval cycle, it performs a lightweight channel check to detect if the camera mode has changed (automatically or externally). If it sees a switch from color to grayscale (or vice versa), it now saves frames with the correct number of channels (one for grayscale, three for color).
Key scenarios this addresses:
•	Automatic in-camera day/night mode changes
•	Operator-triggered mode changes
•	Multiple RMS stations sharing a camera
•	Failed mode changes leaving a camera in an unexpected state
Previously, grayscale frames could be stored in three channels, or the blue channel might be used for compression when cameras changed modes unexpectedly. …
=> Improve handling of color and grayscale frames

.config, RMS/BufferedCapture.py, RMS/CaptureModeSwitcher.py, RMS/Compression.py, RMS/ConfigReader.py, RMS/DeleteOldObservations.py, RMS/Formats/FFStruct.py, RMS/Formats/FTStruct.py, RMS/Formats/FTfile.py, RMS/Reprocess.py, RMS/StartCapture.py
Since the last update that changed the way raw video segments are named and stored, here are the changes this PR makes towards accurate timestamping of these segments:
1. An empty array is initialized to store the pts at the initialization of BufferedCapture.
2. ~~Every call to read() will append a new pts to the array.~~
3. Gstreamer callback moveSegment is called when a clip is ready. The segment is stored in the hierarchy under VideoFiles, while the pts array is flushed to a corresponding FT file under config.data_dir/TimeFiles (configureable), which follows a similar directory structure as the videos (Year/Day-of-Year/Hour/)
4. The timestamp array in memory is immediately cleared to store the next segment's pts.
In addition, each FT file and corresponding video segment are now named …
=> Accurate timestamping for RMS (FT files)

Scripts/RMS_FirstRun.sh, Scripts/RMS_Update.sh, system_packages.txt
Background & Issues in the Original Script
========================================
1. **Risk of Partial Copy/Corruption**
- The original script uses direct `cp` commands on `.config` and `mask.bmp`
- Power loss or error during `cp` leaves files in undefined state
- No validation that copied files match source
2. **No Process Control**
- Multiple instances can run simultaneously
- Concurrent updates can interfere with backup/restore operations
- Stale locks from crashed updates aren't detected or cleaned
3. **No Copy Recovery**
- Single `cp` attempt with no retry on failure
- Failed copy operations halt the script or continue without the file
- No integrity check of copied files
4. **No Space Verification**
- Script attempts operations without checking available space
- Git operations can …
=> Improve Reliability and Safeguards for RMS_Update Script

Scripts/RMS_Update.sh
The PR #505 has a disk space calculation error. When free space exceeds 1TB, `df` outputs scientific notation (e.g. 1.024e+06). The script's `cut -d. -f1` then incorrectly extracts just the first digit, so 1TB free space is misinterpreted as 1MB. This causes the update script to erroneously exit with "insufficient space", preventing updates on systems with >1TB free space until the script is manually fixed.
=> Fix rounding error in free scape calculation

RMS/DownloadMask.py, RMS/DownloadPlatepar.py, RMS/UploadManager.py
We’ve had sporadic reports of lockups that are not reproducible in our test environment. The lockups are happening in UploadManager:
```
2025/01/13 14:28:25-INFO-StartCapture-line:683 - Uploading data before exiting...
2025/01/13 14:28:25-INFO-UploadManager-line:222 - Establishing SSH connection to: gmn.uwo.ca:22...
2025/01/13 14:28:26-INFO-UploadManager-line:76 - Trying ssh-agent key b'b3e09fd48cfea47fcf9d502c74436898'
2025/01/13 14:28:27-INFO-UploadManager-line:81 - ... success!
---------------- HANGS HERE INDEFINITELY --------------
2025/01/13 14:28:27-INFO-UploadManager-line:276 - Copying /home/rms/RMS_data/ArchivedFiles/US001P_20250113_003623_928590_detected.tar.bz2 (60.14MB) to files/US001P_20250113_003623_928590_detected.tar.bz2
2025/01/13 14:29:39-INFO-UploadManager-line:290 - …
```
=> Switch to Paramiko SSHClient with Timeouts & Logging to Investigate Rare Lockups

RMS/DetectionTools.py
Avoid printing 'No mask file has been found' continuously on the console when mask is all white. Also add this info to the log, that will be like this:
2025/01/30 04:46:05-INFO-DetectionTools-line:69 - Loaded mask: /root/RMS_data/config/BR001Z/mask.bmp (all white)
=> Fix mask file log messages in DetectionTools

Scripts/MultiCamLinux/GRMSUpdater.sh
The recent update to GRMSUpdate fixed an issue with usernames containing numbers. However, it introduced a parsing problem with certain display managers, such as LightGDM. See issue #519.
This PR was tested with GDM3 and LightGDM.
=> GRMSUpdate: change parsing handle various display managers

.config, RMS/ConfigReader.py, RMS/DeleteOldObservations.py
- renamed '_frametimes' suffix to '_FT' in DeleteOldObservations
- disabled quota management deletion by default
=> minor changes to space management

RMS/ExtractStars.py
This PR ensures the Gaussian PSF fitting is performed on the raw image data rather than the convolved image.
It keeps the center of mass calculation on the convolved image and only corrects the shift caused by the convolution filter to the center of mass coordinates.
=> Perform Gaussian PSF fitting on the raw image

Utils/SkyFit2.py
This PR increases the visibility of calibration star markers in Skyfit2. Currently, the markers are very hard to see. The new markers have double light-dark rings  designed to be clearly visible against both light and dark backgrounds and to always remain visible behind any size catalog star marker.
=> Increase calstar markers visibility

RMS/EventMonitor.py
This pr is in response to issue #543, and allows times such as 
```
20250319_181910.0
```
to be handled by ignoring the decimal part.
=> Handle times with trailing decimals

.config, RMS/DeleteOldObservations.py
The pull request refers to Issue #549. 
When 
```
logdays_to_keep: 0
```
Deletion of logfiles should be inhibited. This pull request permits log file deletion only when logdays_to_keep > 0.
=> Permit log file deletion only when days_to_keep > 0 

.config, RMS/ConfigReader.py, RMS/DeleteOldObservations.py
This PR is in response to issue #541.
It adds the continuous capture directories into the space quota management system. This is required because the CapturedFiles directory needs to be made smaller to account for the space taken by the continuous capture directories.
It also addresses a new issue. DeleteOldObservations is now being called when capture is in progress. time.sleep calls have been added to prevent dropped frames. 
All files across the three continuous capture directories sorted in time order, newest at the top of the list. An accumulator iterates over the list of files until the size of files matches the quota. The remaining files on the list are deleted. 
```
2025/04/04 13:54:53-INFO-DeleteOldObservations-line:941 - Starting quota based disc space management...
2025/04/04 …
```
=> Add the continuous capture directories into the space quota management system

Utils/GenerateTimelapse.py
Generating timelapse files using too many cpu cores while continuing to capture can cause frames to drop. 
This PR limit mp4 making to one thread.
=> Only use one thread to generate timelapse

Utils/GenerateTimelapse.py
A piece of code was leftover in the generateTimelapseFromFrames causing a failure to generate mp4.
=> Remove leftover code

Utils/GenerateTimelapse.py
Fix syntax issue introduced when some 'print' were recently converted to 'log.info'.
=> Fix syntax in converted print to log entries

RMS/Formats/StarCatalog.py
Revert to years_from_J2000=0 as default, which was the default before a recent update. The recent update left some test code which changed the default to years_from_J2000=None and caused a mismatch type error.
=> Revert to years_from_J2000=0 as default

RMS/Astrometry/ApplyRecalibrate.py, RMS/Astrometry/CheckFit.py
Fix early returns in recalibrateIndividualFFsAndApplyAstrometry and in _handleFailure.
Pass calstars_data instead of calstars_list to _handleFailure.
=> Fix early returns and pass calstars_data to _handleFailure

Utils/CameraControl.py
ClearFog camera setting is not working as it incorrectly set the field value to a 'true', 'false' string. This PR assigns the field a boolean value.
=> Change ClearFog parameter to boolean instead of string type

RMS/BufferedCapture.py, camera_settings.json
Camera image settings become inconsistent after DayNightColor mode changes. Specifically, when switching from night to day mode, images exhibit poor quality (crushed shadows without increased highlight details) until the camera is rebooted. Image quality is restored only after a camera reboot.
This PR implements a camera reboot after mode switching and adds connection verification to ensure proper camera operation.
The revised process flow is as follows:
1. Set camera mode switching flag when capture mode changes.
2. Probe camera connection to verify availability.
3. Apply camera mode switching commands, now including an automatic reboot via camera_settings.json.
4. Wait 5 seconds for the camera to register all commands (NEW).
5. Verify camera connection re-establishment (NEW).
6. Proceed …
=> Reboot camera and check connection after mode switching

Utils/MigrateConfig.py
Adds a new utility script, MigrateConfig.py, that:
1.	Reads existing station .config file (single or multi cam)
2.	Merges it with the latest .configTemplate, carrying forward any non-default values.
3.	Writes the migrated file next to the original (configNew_<CamId> by default), or in a user-supplied location.
4.	Can optionally back-up and replace the active .config in a single --update run.
5.	Logs every change to <CamId>_MigrateConfig.log.
`python -m Utils.MigrateConfig.py`
`python -m Utils.MigrateConfig.py --update`
Key options
-i/--input  path to old .config
-t/--template  template file
-o/--output  write migrated file here
-u/--update  replace live config after backup
-r/--recent  also apply recently-changed template defaults
Implementation highlights
•	Uses …
=> Add utility to upgrade config to configTemplate format preserving attributes

RMS/ConfigReader.py
Currently some quotas allow floats and some only allow int. If a user chooses a float, which is a reasonable expectation, it causes a TypeError.
This PR allows floats for all quota quantities.
=> Allow floats in quota management

RMS/BufferedCapture.py
On occasion, the GStreamer pipeline can hang indefinitely. This tends to happen when multiple concurrent streams are requested. The IMX291 seems to handle up to three concurrent streams per profile. Some IMX307s will hang the pipeline indefinitely when more than one stream is requested (Show LiveStream during capture). 
This PR requests the pipeline to emit frames with a timeout.
=> Add timeout to device.emit

setup.py
RMS is trying to install rawpy on Raspberry Pi that reports the architecture as 'aarch64' rather than just containing 'arm'. This causes an error as rawpy is not available on Pi. This PR prevents attempting to install rawpy on those systems.
=> Rawpy install error on Pi

Utils/MigrateConfig.py
Address issue #595, #596, #597 and #598.
Sections headers are recognized even if followed by inline comments.
Log messages are hopefully less confusing. E.g.:
```
Merging attributes...
[System]stationID: template default 'XX0001' => kept 'US005B'
```
When no valid configTemplate is found, print the following error message:
```
ERROR: Can't find template file /home/ops/source/RMS/.configTemplate
No '.configTemplate' detected. Either:
- run ./Scripts/RMS_Update.sh to create/update it, or
- pass the template path explicitly with -t
e.g.  python -m Utils.MigrateConfig -t /path/to/.configTemplate
```
=> MigrateConfig: recognize config section header even with inline comments

RMS/BufferedCapture.py
If a camera disconnects after the main loop is entered but before the first frame is read, `first_frame_timestamp` is never created, yet the code that writes the FT file still runs and references it.
This PR guards against unset first_frame_timestamp.
=> first_frame_timestamp can be referenced without first being created

RMS/Astrometry/Conversions.py, RMS/BufferedCapture.py, RMS/Compression.py, RMS/DeleteOldObservations.py, RMS/Formats/FTPdetectinfo.py, RMS/Formats/ObservationSummary.py, RMS/Logger.py, RMS/Misc.py, RMS/StartCapture.py
The datetime.datetime.fromtimestamp function is not timezone aware and might produce data files with times set to localtime if the machine is not set to UTC.
The proposed change handles this on all python versions.
=> Always force UTC time for all data products

Utils/MigrateConfig.py
By user request, this PR prints the location of the dry-run output in the terminal.
=> Add informational print to MigrateConfig dry run output

RMS/Logger.py
This reverts a4bd454 "removed duplicated code while preventing circular imports" which unfortunately broke RMS.Reprocess and possibly some other standalone modules (see Issue #639 )  My google search did not find any workaround for this, so for now I think we'll have to live with the duplication until we cease support for Python 2.7 and can replace mkdirP and the utc-handling classes with generic Python 3.x code throughout the entire codebase.
=> Rollback changes ref circular dependencies

Utils/GenerateTimelapse.py
Remove DOY from frame timelapse filename to make it sortable chronologically.
```
US005C_156_20250605-032240_to_20250605-113024_frames_timelapse.*
to
US005C_20250605-032240_to_20250605-113024_frames_timelapse.*
```
=> Remove DOY in frame timelapse name

RMS/QueuedPool.py
This PR makes sure we never pass zero core to multiprocessing.Pool.
=> Safeguard against corrupted core value

Scripts/RMS_Backup.sh
This PR relates to issue #644.
The mask and platepar files are no longer listed in the .config file, which is limiting the functionality of the RMS_Backup.sh script
This PR hard codes the names of the mask and platepar file into the backup script. It removes a flag --junk-paths, which may not have been functioning on some systems. This preserves the directory structure of a multicamera station, and stops files with the same name, but different paths clobbering each other. A consequence of this is that the whole .ssh directory is backed up, not just the key files. 
The old version of the file prints to terminal as below.
```
(vRMS) david@lap-deb-01:~/source/RMS$ Scripts/RMS_Backup.sh 
realpath: '': No such file or directory
realpath: '': No such file or directory
RMS Backup
---------- …
```
=> Do not use config file settings for backup

RMS/Formats/ObservationSummary.py
This PR relates to issue #641 and reduces the precision of the observation summary file, and uses the features of chrony, ntpstat, ntpq, or a fallback to a direct query on a remote time server to estimate time error and uncertainty. 
The values added are 
```
clock_measurement_source        : chrony 
clock_synchronized              : True 
clock_ahead_ms                  : 1.817 
clock_error_uncertainty_ms      : 47.129 
```
The keys are ordered to improve readability.
```
stationID                       : AU002C 
commit_date                     : 20250615_071249 
commit_hash                     : 115ff0e8985978044a7fa3415dd4867c59757c0f 
hardware_version                : x86_64 
captured_directories            : 24 
storage_used_gb                 : 2405.52 
storage_free_gb …
```
=> Remove unwarranted precision from observation summary text file, add time error, catalog in use and other keys

RMS/CaptureModeSwitcher.py
Currently, there is an error when computing the time_to_wait before switching mode if capture_wait_seconds is not zero (used to stagger switching in a multi-camera setup). The time_to_wait uses a current_time that is no longer current by the time of the calculation. 
This PR uses a fresh current time.
=> Refresh current time before computing time to wait

RMS/CaptureModeSwitcher.py
A copy-paste error in a recent change inadvertently replaced next_rise with next_set. This PR corrects the error.
=> Fix next_rise error

Utils/FOVSkyMap.py
Original behavior was for FOVSkyMap to write output to same directory as files were brought from. This PR restores that functionality. 
```
(vRMS) david@lap-deb-01:~/source/RMS$ python -m Utils.FOVSkyMap ~/source/RMS/Tests/Stations
FOV sky map saved to: /home/david/source/RMS/Tests/Stations/fov_sky_map.png
```
If a path is given with no filename, at appends default of fov_sky_map.png
```
(vRMS) david@lap-deb-01:~/source/RMS$ python -m Utils.FOVSkyMap ~/source/RMS/Tests/Stations -rl -o ~/tmp
FOV sky map saved to: /home/david/tmp/fov_sky_map.png
```
If a path and filename is given then that path and filename is used
```
(vRMS) david@lap-deb-01:~/source/RMS$ python -m Utils.FOVSkyMap ~/source/RMS/Tests/Stations -rl -o ~/tmp/Station.png
FOV sky map saved to: /home/david/tmp/Station.png
```
It …
=> Restore original output location if no output destination specified

RMS/DeleteOldObservations.py
If quota management is enabled, then logging is limited to first 100 files, however no limit is applied if quota management is disabled. This PR fixes that, and also prevents any quota management work being carried out if quota management is not enabled.
=> Prevent logging of excessive files if quota management is disabled

.config, RMS/BufferedCapture.py, RMS/ConfigReader.py, Utils/AuditConfig.py
Currently, frames are saved every nth frames from whenever the first frame is read. This PR save frames every nth seconds from a reference epoch. This allows synching frame capture across multiple cameras.
The interval is set to 5 seconds and is not exposed in .config. (ConfigReader only).
A frame is saved when its timestamp is within 0.5/fps seconds from a sync tick mark.
=> Save a frame every nth seconds from a reference epoch

RMS/ConfigReader.py
save_frames unintentionally defaults to False when the option is not present in the config file.
=> Fix save_frames unintentionally defaulting to False

RMS/BufferedCapture.py
This PR addresses a bug when raw_video_save is enabled on older GStreamer (e.g. GStreamer 1.16 on Ubuntu 20.04).
On older GStreamer versions, splitmuxsink ignores muxer-factory=matroskamux and uses qtmux instead, causing:
- Memory leak: qtmux keeps growing frame tables in RAM (stts/stco)
- Shutdown hangs: Large files block pipeline teardown indefinitely on very long runs
- Log spam: "reserved-moov-update-period" warnings every 30 seconds
Adding `async-finalize=true` enables the muxer-factory setting. This makes splitmuxsink actually use matroskamux, which streams headers incrementally.
Tested on Ubuntu 20.04 and 24.04.
=> splitmuxsink: add async-finalize=true so muxer-factory is honoured

RMS/Astrometry/ApplyRecalibrate.py, RMS/Astrometry/CheckFit.py, RMS/Astrometry/FFTalign.py, RMS/BufferedCapture.py, RMS/DeleteOldObservations.py, RMS/DetectStarsAndMeteors.py, RMS/Detection.py, RMS/DownloadMask.py, RMS/DownloadPlatepar.py, RMS/Logger.py, RMS/MLFilter.py, RMS/Reprocess.py, RMS/StartCapture.py, RMS/UploadManager.py, Utils/CameraControl.py, Utils/Flux.py, iStream/iStream.py
RMS.Astrometry.ApplyRecalibrate didn't run as a standalone script as it failed to find the SITE_DIR global variable. I completely removed the use of globals, but left them initialized in case they're used outside of RMS.
=> Fix missing SITE_DIR bug in scripts not calling the logger

Utils/CameraControl.py
By design this standalone module needs to send output to the console.  Unfortunately a change to the logger suppresses output unless stdout=True is added to the call to getLogger(). This PR adds that 
I'm unsure when this bug was introduced, and a check of the git logs doesn't help, However my stations were working correctly on 26/07 but broken by 28/07 so i would guess the issue was introduced between those dates, possibly by merging an older PR that had unintended side effects. I'll see if i can add an automated test of CameraControl to my test suite.
=> reinstate console output in CameraControl

RMS/VideoExtraction.py
```
2025/07/31 11:59:27-INFO-VideoExtraction-line:289 - Nothing found, not extracting anything  from AU000A_20250731_115909_211_0143872
```
Contains a double space. This PR removes the double space addressing #693 
```
2025/07/31 13:42:32-INFO-VideoExtraction-line:289 - Nothing found, not extracting anything from AU000A_20250731_134210_456_0018176
```
=> Remove double space

Utils/FOVSkyMap.py
Adds option for a plot of the sun position as seen from one station for each hour over the next year. 
```
python -m Utils.FOVSkyMap -fircn /home/david/source/RMS/Tests/Stations/ -o /home/david/tmp -s
```
or
```
python -m Utils.FOVSkyMap -fircn /home/david/source/RMS/Tests/Stations/ -o /home/david/tmp --show_sun
```
Also can show the moon position, every 5 minutes over the next 29.5 days.
```
python -m Utils.FOVSkyMap -fircn /home/david/source/RMS/Tests/Stations/ -o /home/david/tmp -m
```
or
```
python -m Utils.FOVSkyMap -fircn /home/david/source/RMS/Tests/Stations/ -o /home/david/tmp --show_moon
```
=> Plot sun, moon and arbitrary number of RaDEC defined objects on FOVSkyMap

Scripts/RMS_FirstRun.sh
An onscreen message advises the user not to close the window "until RMS starts", but in fact RMS runs in the same window, so closing the window kills RMS. A few users have been known to do this and were then disappointed that RMS "didn't work". 
This PR changes the message a little to hopefully avoid that issue.
=> update onscreen message

RMS/Logger.py
- Added sequence numbers to log filenames to make it obvious when logs are continuations from previous files
- Log files now include a 3-digit sequence number (e.g., `log_STATION_20241227_120000_001.log`)
- Sequence increments on each rollover, making it clear which logs belong to the same session
```
log_STATION_20241227_120000_001.log
log_STATION_20241228_120000_002.log
log_STATION_20241229_120000_003.log
```
=> Add sequence numbers to log filenames for continuity tracking

RMS/BufferedCapture.py, RMS/Compression.py, RMS/RawFrameSave.py
Fix hang on backend mismatch.  Cleanup now checks the actual object (hasattr(device, "release") vs set_state) instead of trusting the video_device_type flag, so a GstAppSink is never routed through cap.release().
- Timeout-protected OpenCV release: cap.release() runs in a daemon thread with a 2 s join; if it stalls we drop the FD and log a warning rather than block forever.
- Unified teardown: always sets device to None and handles Gst to NULL, making multiple calls to releaseResources() idempotent.
- Extra DEBUG logs: added around state transitions, cleanup branches, and timeout paths to pinpoint future stalls.
Python has no safe built-in way to abort a running C call in another thread, so there is a bit of trial and error on my part to see what works and what doesn't. The number of …
=> Safeguard releaseResources and add diagnostics

RMS/UploadManager.py
UploadManager previously made five upload attempts ten seconds apart. During heavy network load this could burn all retries in under a minute, after which the manager waited for the next fifteen-minute cycle.
This change keeps the retry limit at five but replaces the fixed delay with exponential backoff starting at fifteen seconds and doubling on each failure, capped at eight minutes. The new delays are 15, 30, 60, 120 and 240 seconds.
The result is lower server burst traffic while still recovering quickly from brief outages. The uploader will never sleep for more than about eight minutes, so the outer fifteen-minute schedule remains meaningful.
The retry loop is now wrapped in a try-finally block to ensure the upload_in_progress flag is always cleared.
=> UploadManager: replace fixed-interval retries with exponential back-off
