CroatianMeteorNetwork/RMS

RMS/DeleteOldObservations.py
RMS calculates how much storage space it needs for the night and when free space is insufficient, the oldest folders from RMS_data/ArchivedFiles and RMS_data/CapturedFiles are removed until enough storage space is available.
Code currently gives up when no folders are left to delete, however there's still some compressed captures left on RMS_data/ArchivedFiles that could be removed as well. This patch adds the ability to remove these files as last resort when no free storage space is available.
=> delete archived .tgz files too when no free space is available

RMS/ArchiveDetections.py, RMS/Reprocess.py
This patch fixes python crash found when trying to reprocess BR0001 night containing bad/corrupted data.
=> fix crash while reprocessing a night with bad data

RMS/RunExternalScript.py
RunExternalScript is currently printing diagnostic messages to stdout. This patch makes those messages appear on RMS log files.
=> make RunExternalScript use standard log mechanism

Utils/SkyFit2.py
While waiting for my camera to arrive, I'm getting some code to work on my computer.
Note that the file dialogs still need to be ported to Qt.
I have not tested this on python2.
=> Migrated some tkinter to qt

Utils/CameraControl.py, Utils/CameraControl27.py, Utils/GenerateMP4s.py
1) fix bug reported by Megan  - using incorrect ftpdetect file
2) add the following to CameraControl
- enable/disable time and station name OSD 
- enable and disable NTP server
- manage Color Settings dialog otherwise only accessible through CMS
- saving and reloading all the above via Save/LoadSettings
=> Fix to generateMP4 and improvements to CameraControl

Scripts/RMS_SetCameraParams.sh
Fix the problem with "./Scripts/RMS_SetCameraParams.sh: line 99: syntax error: unexpected end of file".
=> Fix camera syntax

Utils/FFtoFrames.py, Utils/GenerateMP4s.py
This PR will make the time indicator in the generated MP4 reflect the actual time, not the time from the FF file from which it was extracted.
=> Update timestamp in GenerateMP4s

Scripts/RMS_watchdog.sh
Modified RMS_watchdog.sh to make a more targetted kill command so that other python apps running on the Pi are not also killed abruptly.
=> Watchdog update

.config, RMS/BufferedCapture.py, RMS/ConfigReader.py, Utils/ShowLiveStream.py
This may increase performance for direct video devices (/dev/video0).
=> Add flag to force cv2 to use V4L2

RMS/Routines/Image.py, Utils/BatchFFtoImage.py
Add an optional parameter to saveImage to allow a title to be added at the bottom left corner. 
Add optional argument to BatchFFtoImage to invoke this new code. 
The title is of the form "XX0001 YYYY-MM-DD HH:MM:SS UTC"
Tested on UK0006 and UK000F for a couple of weeks without issue. 
Note that saveImage is called from Compression, Reprocess, FRBinMosaic, MakeFlat, ManualReduction, SkyFit2, StackFFs, StackImgs.  No problems were observed with these modules which have not been altered.
=> Optionally, add title to jpegs

.config, Utils/GenerateTimelapse.py
It avoids having it stuck waiting for user/keyboard input (using 100% of a CPU, sometimes)
=> GenerateTimelapse: Add -nostdin option to ffmpeg

Utils/ShowLiveStream.py
The index of green channel is 1.
=> Fix use of green channel in Live stream

RMS/DeleteOldObservations.py
bugfix to prior pull request. Sorry, didn't spot it till too late.
=> need to make sure logdays_to_keep is an int

Scripts/RMS_Backup.sh
It creates a .zip file containing the important config files that
should be preserved for repairing or replacing a RMS station.
=> add RMS_Backup.sh script

RMS/MLFilter.py
This is the enhancement following comments by Alfredo and Mark.
No PNG pictures are deleted now, available for manual check, and overwritten during the next run.
The prediction value is now appended to the filename (3 digits).
Threshold (-t 0.95) is now part of the command line.
Some minor bug fixes in addition.
=> Create 'meteors' and 'artefacts' subdirs, threshold as argument

RMS/MLFilter.py
- optionally keeping the pngs:  -p 0 will delete them. Default / -p 1 will keep them. 
- rerunning with different threshold and  saving the modified ftpfiles with unique names for later review
When rerunning the module, if the _unfiltered file exists, then this is used in place of the FTPdetect file passed in on the commandline. This allows one to run and rerun the script with different thresholds more easily, and without having to think about whether the module was already run on the folder. 
The resulting filtered ftpdetect file is also copied to a 2nd file with the threshold in its name so you can compare the output of different runs. 
I also tidied up a couple of unused variables and some non-standard indentation which would have caused some versions of Python to error out.
=> Added support for making PNG retention optional, and rerunning on the same folder. 

Utils/TrackStack.py
Largely work done by @tammojan but with some work by @markmac99 to handle error conditions and simplify the code:
Adding the ability to create a trackstack filtered by shower eg -s PER, and to create a trackstack for multiple days, and to set the output folder 
python -m Utils.TrackStack dir1 dir2 dir3 -s showerlist -o somewhere
dir_path can be a list of folders for example different nights of a shower
-s showers - optional, comma-separated list of showers e g PER,cap,ARI (case insensitive)
-o somewhere - optional, save the output in a different location to avoid overwriting an existing trackstack
-d optional, set blackpoint to minimum detected value (darkens sky considerably, may be undesirable for some users)
Note: shower-filtration requires the FTPdetect files and a valid .config file …
=> Enhancing TrackStack

RMS/MLFilter.py
Return value changed, to enable integration into pipeline.
Default threshold changed to 0.85, will be kept in .config in the future.
Minor cosmetic fixes.
=> Bug and other fixes

Utils/FOVSkyMap.py
Add option to plot FOVSkyMap with north up and azimuth increasing clockwise. 
Without -n
With -n
=> Add northup option to FOVSkyMap

RMS/Astrometry/Conversions.py, RMS/EventMonitor.py, Tests/EventMonitorTests.py
Added ability to define trajectory with single point and an az el
=> Eventmonitor

Scripts/RMS_SetCameraParams.sh
Incorrect spelling of WhiteBalance, pointed out by Yong-Ik
=> Fix in RMS_SetCameraParams.sh

RMS/EventMonitor.py
Request for log entry to be made on each iteration of event monitor, added logging of start time so that this does not scroll off the screen.
=> Log each run of EventMonitor and write start time.

RMS/EventMonitor.py
More work on handling CapturedFile directories with missing .config and platepar files.
More robust determination of fallback directory for multi-camera stations
The additional commenting is to assist with debugging on multi-camera stations.
=> Multi camera gui platepar

RMS/EventMonitor.py, RMS/Misc.py
https://github.com/CroatianMeteorNetwork/RMS/issues/218
Modifies existing event_monitor.db file by adding a suffix column if this column is missing
Sanitises a suffix field, loads into database, and then adds as a suffix to the archive file
```
AU002A_20230913_151600_test-2.tar.bz2
```
was created from
```
EventTime                : 20230913_151600
TimeTolerance (s)        : 35
EventLat (deg +N)        : -32.34301
EventLon (deg +E)        : 116.60553
EventHt (km)             : 95.80500
CloseRadius(km)          : 1000.00
FarRadius (km)           : 6000.00
EventLat2 (deg +N)       : -32.37110
EventLon2 (deg +E)       : 116.81883
EventHt2 (km)            : 81.24380
Suffix			 : te.s.><t-2
```
=> Allow archive suffix to be defined

Utils/FRbinViewer.py
fixed for:
#222 Video for created from FR bin can not be played in some OS by standard players
#201 FRbinViewer - add timestamp to video like in BatchFFtoImage
#200  FRbinViewer - fit window to screen size when playing Full HD bin files
=> Bin viewer improvements

RMS/Astrometry/AtmosphericExtinction.py
This is my first attempt at working on the code, so am keeping it simple to check my pull request works correctly.
=> Correct the spelling in the Astrometry/AtmosphericExtinction.py file.

RMS/ConfigReader.py, RMS/DownloadMask.py, RMS/Reprocess.py, RMS/StartCapture.py, RMS/UploadManager.py
New feature to allow an updated mask to be downloaded from remote server
=> Download mask from remote

Utils/SkyFit2.py
Add CTRL + G keyboard hint for cycling between grids
=> Fix SkyFit2 keyboard hint

Utils/FRbinViewer.py
Hi, 
As I can see my everyday usage of FRbinViewer it is  generating meteor mp4 video for bin files with options:
- --avg - use average pixel for background to generate pure video of meteor (with black background)
-  --timestamp - add date and time information to video
Usually bright and cool meteors shared with friends or social media and it requires additional action - append final image of meteor to the end of video for 1 or 2 seconds by some video editor.
In this pull request I added two additional  options:
- --append_ff_to_video - append to the end of video ff fits image (max pixel) for 1.5 seconds
- --add_shower_name - add same as timestamp to video shower name which detected by showerAssociation for single station
Probably these options will be helpful for someone.
Tested on Mac …
=> FRbinViewer - append meteor image to the end of video and add meteor shower information

RMS/EventMonitor.py, RMS/Misc.py
This pull request relates to https://github.com/CroatianMeteorNetwork/RMS/issues/240 
It implements a new command to EventMonitor which only allows upload if an FR*.bin file was generated within the event window. This is intended to reduce the number of stations which upload for a bright event when the trajectory has a large uncertainty. 
```
EventTime                : 20240209_191741
TimeTolerance (s)        : 30
EventLat (deg +N)        : -34.549697
EventLon (deg +E)        : 117.59325
EventHt (km)             : 100.5
EventLat2 (deg +N)       : -35.0
EventLon2 (deg +E)       : 117.0
EventHt2 (km)            : 30
CloseRadius(km)          : 500
FarRadius (km)           : 1000
RequireFR		 : 1
END
EventTime                : 20240209_191740
TimeTolerance (s)        : 30
EventLat (deg +N) …
```
=> Feature require fr

RMS/EventMonitor.py
Handle corrupted databases by deleting and recreating, then pausing the EventMonitor thread
=> EventMonitor database recreation

.config, RMS/BufferedCapture.py, RMS/ConfigReader.py, RMS/Formats/FrameInterface.py, RMS/Routines/Image.py, RMS/StartCapture.py, Utils/PlotTimeIntervals.py, Utils/SkyFit2.py, opencv4_install.sh, requirements.txt, setup.py
To increase the accuracy of timestamps, `BufferedCapture.py` was refactored to utilize GStreamer Presentation Timestamp (pts) feature, which is unaffected by client latency.
`PyGObject` is now required in vRMS, which has been added to `requirements.txt`.
Alternatively, for testing purposes, execute `pip install PyGObject` within vRMS.
OpenCV continues to be utilized for processing video files (though this remains untested) or if `force_v4l2` is set to `true` in `.config` (also untested). If desired, a `force_cv2` flag could similarly be added. Otherwise, a GStreamer pipeline utilizing software decoding through `avh264dec` is employed. the code has been tested with GStreamer1.0 v1.22 - compatibility with v1.14.4 remains untested.
Ad-hoc latency adjustments specific to IMX291 IP cameras are …
=> Enhanced Timestamping Using GStreamer Presentation Timestamp (pts)

Utils/PlotTimeIntervals.py
Changes to **'Utils/PlotTimeIntervals.py'**:
- Fix horizontal axis tick labels formatting bug with older matplotlib versions.
- Fix wrong FPS Standard Deviation calculation.
- Set max vertical scale value to 60s.
- Fix horizontal grid line anomalies.
- Increase the number of decimals shown for FPS in the legend.
=> Fix various PlotTimeIntervals issues

Utils/PlotTimeIntervals.py
In my previous fix, the calculation for the fps standard deviation was still not accurate. This should resolve the issue. I also incorporated more style and comments cleanup.  Thank you for your understanding.
Luc
=> Fix fps standard deviation calculation again

Scripts/MultiCamLinux/RMS-screen.sh
Allow user to launch screen sessions, one for each configured MultiCam station
=> Headless aid

README.md, RMS/Reprocess.py, Utils/PlotTimeIntervals.py
Address issue #292 where a capture containing fewer than 3 FITS files would generate an error.
=> Fix Timestamp Interval Plot Error Message on Very Short Capture

Scripts/RMS_Update.sh, requirements.txt
Addresses issue #322 by using pyclean as suggested by @markmac99.
The `pyclean` module is added to requirements.
There will be a 'pyclean not found' error on initial update as the pyclean command is issued before `pip install -r requirements.txt`. However, the error disappears on the second update.
=> Use pyclean before updating

RMS/Formats/FFbin.py, RMS/Routines/AllskyPlot.py
Added 'r' prefix to regex patterns and 'u' prefix to Unicode strings containing special characters to ensure compatibility with both Python 2.7 and 3.x, resolving SyntaxWarnings.
=> Silence Syntax warning

.config
=> Fixes #354 Cleanup up syntax  in .config

RMS/Astrometry/ApplyAstrometry.py, RMS/Astrometry/ApplyRecalibrate.py, RMS/CaptureDuration.py, RMS/DeleteOldObservations.py, RMS/DetectStarsAndMeteors.py, RMS/DownloadMask.py, RMS/DownloadPlatepar.py, RMS/EventMonitor.py, RMS/Formats/FTPdetectinfo.py, RMS/Logger.py, RMS/Misc.py, RMS/Routines/SolarLongitude.py, RMS/StartCapture.py, RMS/UploadManager.py, Utils/FluxAuto.py, Utils/FluxFitActivityCurve.py, Utils/GenerateMP4s.py, Utils/GenerateTimelapse.py, Utils/SaturationCorrection.py, iStream/iStream.py
Sorry, it was too time consuming to modify PR #313 so I recreated it here. Thank you, @adalava for your work on this.
=> Utcnow fix

RMS/Formats/ObservationSummary.py
#366  The repo is not found on the parent dir on multicam station. Would it be sufficient to point to ~/source/RMS and wrap it in a try?
=> Fix #366: Resolve Multicam repo folder location bug

RMS/Formats/ObservationSummary.py, RMS/Reprocess.py
Variable pp may not be set after a night of heavy cloud, therefore reading in the station platepar
=> Read in platepar rather than relying on existing variables

RMS/Routines/AllskyPlot.py
Address #377 by reverting error introduced in PR #350.
=> Revert error introduced by PR #350

Utils/TrackStack.py
Fix for trackstack bug #380 - i will test it today and comment
=> Fix for #380

requirements.txt
Addresses #351. Need to test that SSH connections still work with python 2 & 3.
=> Change requirements to paramiko>=2.9.0

RMS/Formats/ObservationSummary.py
=> Revert commit by deleting getRmsRepo()

RMS/Astrometry/ApplyRecalibrate.py, RMS/Formats/Platepar.py, RMS/Reprocess.py, RMS/Routines/MaskImage.py, Utils/Flux.py, Utils/RecomputeCollectionAreas.py
All raw collecting areas on operational systems have been computed without masks. This PR fixes that, hopefully resulting in correct fluxes.
=> Fix loading operational mask when computing flux

RMS/Math.py
Requesting recent changes in master are merged into prerelease.
=> Merge master into prerelease

RMS/Formats/ObservationSummary.py
This pull request is in response to issue #430 and removes a redundant print call
=> Comment out print call

RMS/BufferedCapture.py
This should fix the GStreamer pipeline blowing up on slow machine by reverting the queue settings to what they were before introducing branching.
Testing in progress...
=> Fix GStreamer pipeline queues

RMS/Formats/ObservationSummary.py, RMS/Reprocess.py
Add try-except block to Observation Summary to troubleshoot reports of reprocess hanging.
=> Add try-except block to Observation summary

RMS/BufferedCapture.py
There's been instances where a camera would disconnect in gst mode, then successfully connect in cv2, then disconnect again but reconnect back to gst. This causes the program to be confused about which mode it's in. With this PR, once falling back to cv2 the program will not attempt to go reconnect in gst mode for the remainder of the session.
=> Prevent fallback to GST after GST and subsequent CV2 failure.

RMS/Astrometry/ApplyAstrometry.py, RMS/Astrometry/Conversions.py
Add image XY + Height to Lat Lon function.
=> Add XyHt2Geo function

RMS/BufferedCapture.py
Currently, the code performs simple pings to the camera prior to attempting to start an RTSP stream. However, the ping may be successful even though the RTSP server is not up. Alternatively, the ping may fail for reasons not related to the camera, such as the network interface being down. This PR replaces the simple ping check with an RTSP service connection probe that provides detailed connection status and error handling.
- Replace basic ping with socket-based RTSP service availability check
- Add detailed error classification for network, host, and service-level issues
- Implement retry mechanism with configurable attempts and intervals
- Add detailed logging for debugging connection issues
- Remove the 5 second wait after a successful ping as it is now testing the RTSP service …
=> Replace Ping with RTSP Service Connection Probe

.config, RMS/BufferedCapture.py, RMS/CameraModeSwitcher.py, RMS/ConfigReader.py, RMS/DeleteOldObservations.py, RMS/Formats/ObservationSummary.py, RMS/RawFrameSave.py, RMS/Reprocess.py, RMS/StartCapture.py, Utils/CameraControl.py, Utils/GenerateTimelapse.py
This PR adds continuous daytime capture feature to the capture code. When enabled, the code runs capture throughout day and night, while also switching between the implemented daytime and nighttime modes within CameraControl.py.
=> continuous daytime capture

RMS/ConfigReader.py
=> Fix video_dirs_to_keep variable name

RMS/StartCapture.py
=> Initialize daytime_mode even when not in continuous capture

RMS/Reprocess.py
commented out timestampRMSVideos as it is to be reimplemented
=> commented out call to timestampRMSVideos (Reprocess.py)

RMS/DeleteOldObservations.py
Updated deletion for raw frame files (FramesFiles). Inside the frames file folder, the program will now look for and delete processed files (archives, timelapses, and json) only and not directories - which may currently be unprocessed or in processing state.
=> updated deletion methods for raw frames (DeleteOldObservations.py)

RMS/StartCapture.py
Updated StartCapture flow:
- In continuous mode, when a switch from nighttime to daytime occurs, post-processing runs along with BufferedCapture's continued capturing.
- In standard capture mode, when capture is stopped, then BufferedCapture is stopped before post-processing begins and not after. (This PR aims to restore this intended behaviour of standard capture mode).
=> corrected standard capture mode flow

RMS/Logger.py
-  Added pre-initialization logging support to capture DEBUG and INFO messages during import time
-  Implemented PreInitNoiseFilter to suppress common noise patterns during module imports
-  Fixed missing line numbers in log messages
-  Set DEBUG as default log level for new logger instances
=> Logger adjustments

RMS/StartCapture.py
CTRL+C always stops capture immediately, regardless of the value of config.continuous_capture.
Post-processing always follows after capture has stopped. 
Solves the initial problem from issue #482 .
=> Corrected capture termination flow

RMS/Math.py, RMS/Routines/SphericalPolygonCheck.py, Utils/Flux.py
Addresses #510
In addition, the function which checks whether a set of (ra, dec) is inside a polygon was faulty. I developed a new robust approach.
=> Fixed spherical polygon check and magnitude calculation for star number prediction

RMS/DownloadMask.py, RMS/DownloadPlatepar.py, RMS/UploadManager.py
This PR fixed a bug that cause RMS to crash when SSH authentication failed.
=> Fix crash caused by invalid RSA key

RMS/BufferedCapture.py
On occasion cv2 returns None Frame type, which caused an uncaught exception in `handleGrayscaleConversion`.
`handleGrayscaleConversion` now checks for None type first.
=> Fix 'NoneType' object is not subscriptable in handleGrayscaleConversion

RMS/Reprocess.py
=> updated FT file archive name

RMS/StartCapture.py
=> Fix Type error in StartCapture (prerelease)

.config, RMS/ConfigReader.py, RMS/StartCapture.py
Suggested fixes for Issue #520
=> fix for auto reprocessing during standard capture

Scripts/RMS_Update.sh
Address Issue #536 by making the lock file user specific.
(Typing this on the road - did not test yet)
=> Change from global to user specific lock file

RMS/Logger.py
Change log date from YYYY-MM-DD to YYYYMMDD
=> Change log date from YYYY-MM-DD to YYYYMMDD

.config, RMS/BufferedCapture.py, RMS/ConfigReader.py, RMS/Logger.py, RMS/Misc.py, RMS/RawFrameSave.py, RMS/Reprocess.py, RMS/UploadManager.py, Utils/GenerateTimelapse.py
This PR changes frame timelapse and timestamps JSON generation process.  Frames Timelapse are now generated using a streaming approach, eliminating the need for temporary storage and reducing peak disk usage. It introduces atomic file operations with proper cleanup to enhance error handling and recovery. Video encoding parameters have been adjusted for better cross-platform compatibility, improved quality, and faster processing while maintaining the current file size. Corrupted frames are now skipped in both the timelapse video and the timestamp JSON sidecar file. The timestamp JSON generation has been refactored to reliably reflect actual frame timestamps and is generated as frames are added to the timelapse. Failed attempts are now cleaned up and retried automatically during subsequent …
=> Optimized Timelapse and Timestamps JSON Generation Process

Scripts/RMS_Update.sh
This PR address an issue where RMS_Update would exit without restoring custom config and mask files if git pull failed.
=> Address RMS_Update not restoring custom files

RMS/StartCapture.py
Fix error when attempting to copy config file in non existing night data directory in daytime mode.
Fix error when using StartCapture -d with continuous mode enabled in config. 
Fix other remote edge cases.
=> Fix errors in daytime mode and other edge cases

RMS/Astrometry/FFTalign.py
datetime.datetime milliseconds should be int not float.
=> Fix millisecond type error

RMS/BufferedCapture.py
Address issue #577 by initializing shared boolean flags.
=> Initialize shared boolean flags 

RMS/Astrometry/ApplyRecalibrate.py, RMS/Astrometry/CheckFit.py, RMS/Astrometry/FFTalign.py, RMS/Formats/StarCatalog.py, Utils/CalibrationReport.py
=> Guard against empty Calstar lists

RMS/BufferedCapture.py
Drain the GstBus completely: poller now pops MessageType.ANY, so no message backlog can build up.
Manage the poller thread: keep a handle in self._bus_thread, join() it on every reconnect/shutdown, and clear it after the join.
=> Drain any messages from the GST bus and properly exit busPoller

RMS/BufferedCapture.py
Currently, the dropped frame count using the CV2 backend method is broken. It reports late frames based on instantaneous frame retrieval time, which overcounts late or dropped frames compared to the mean in a 256-block. This PR uses a block mean interval to estimate dropped frames.
=> Fix stats reporting with CV2 backend

.config, RMS/BufferedCapture.py, RMS/Formats/StarCatalog.py
Fix a typo in a config variable name and fix style issues.
=> Fix typos and style

.config
any of the five quota parameters missing or none will disable quota management
=> Update quota comment

RMS/Formats/ObservationSummary.py
Currently, if ObservationSummary is querying a camera while it's being rebooted no camera info is logged. This is likely on more-than-one-computer-per-camera setups.
This PR queries the camera type with retries.
=> Gather Camera Information with retries

RMS/StartCapture.py
Include a tribute to deceased members of the Global Meteor Network within the runCapture function.
=> Add memorial note for Global Meteor Network members in runCapture function

Utils/MigrateConfig.py
=> Remove erroneous 'continue'

.config
=> Expand explanatory comment for switch_camera_mode

RMS/CaptureModeSwitcher.py
In MCL, it is recommended to stagger camera mode switching with capture_wait_seconds to avoid power spikes. This PR takes this into account for bundling frames to generate timelapses. Currently, it leaves one frame out per 5-second delay.
Additionally, the delay was introduced in the neverup and neverdown cases, which is not needed. This PR removes those unneeded delays and expands code comments.
=> Fix frame timelapse not accounting for capture_wait_seconds

Scripts/RMS_Update.sh
RMS_Update would delete build directories and then leave RMS in a broken state if anyting went wrong, never running "python setup.py install".
All "exit" commands have been removed, making sure RMS still runs even if something goes wrong with the update.
A function was added that tries to recover the RMS repository if it goes corrupted.
=> Make RMS_Update less rigorous

Utils/GenerateTimelapse.py
This PR relates to issue #670, and restores command line function. 
When passing a directory to GenerateTimelapse, no timelapse is created.
```
(vRMS) david@lap-deb-01:~/source/RMS$ python -m Utils.GenerateTimelapse /home/david/RMS_data/CapturedFiles/AU000A_20250626_100356_303966/
Timelapse Generator Configuration:
Input directory: /home/david/RMS_data/CapturedFiles/AU000A_20250626_100356_303966/
Output video: /home/david/RMS_data/CapturedFiles/AU000A_20250626_100356_303966/AU000A_20250626_100356_303966_timelapse.mp4
FPS: 30
CRF value: 25
Cleanup mode: none
Video mode: Color
Starting process at: 2025-07-01 10:49:43.996443
generateTimelapseFromDir: no images found in /home/david/RMS_data/CapturedFiles/AU000A_20250626_100356_303966/
Process completed at: 2025-07-01 10:49:44.006914
Total …
```
=> Restore CLI function for Utils.GenerateTimelapse

RMS/BufferedCapture.py, RMS/Compression.py, RMS/DetectStarsAndMeteors.py, RMS/DetectionTools.py, RMS/EventMonitor.py, RMS/ExtractStars.py, RMS/Formats/FrameInterface.py, RMS/Routines/Grouping3D.py, RMS/UploadManager.py, RMS/VideoExtraction.py, Utils/CameraControl.py, Utils/Flux.py, Utils/StackFFs.py
This update changes logging level of a few messages so that more is reported at the INFO level and a some mainly duplicated mesasges are dropped to DEBUG. It also updates the camera reboot message to clarify that its the camera rebooting.
Specific changes in logging are
* in Compression
* change compression time to INFO so it can be monitored for issues
* change saving time to INFO so it can be monitored for issues
* in DetectStarsAndMeteors, change "at least x stars" message to INFO so it can be monitored for issues
* in VideoExtraction change "nothing found" message to INFO so it can be monitored for issues
* in FrameInterface, add logging as previously it was using print statements so logs lost entirely!
* in ExtractStars change "extracted stars" to DEBUG as its already reported at …
=> Proposed changes to logging levels

RMS/Routines/FOVSkyArea.py, Utils/FOVSkyMap.py
Introduce functions for calculating the area of the sky covered by a camera's field of view (FOV) using a platepar file. Integrate this functionality into the existing plotting routines to display the FOV area.
=> Add functions to compute FOV area in square degrees

RMS/UploadManager.py
Fixed a multiprocessing bug where timing variables (`last_runtime` and `next_runtime`) were not shared between parent and child processes, causing upload delays to be ignored and preventing proper coordination during shutdown.
- UploadManager inherits from `multiprocessing.Process`
- When `upload_manager.start()` is called, it creates a new process with separate memory
- Parent process sets timing via `addFiles()` and `delayNextUpload()`
- Child process runs the upload loop but couldn't see parent's timing changes
- This caused:
- Upload delays to be ignored
- Files not uploading before program exit
- Coordination issues during shutdown
- Changed timing variables to use `multiprocessing.Value('d', 0.0)` for shared memory
- Used raw Unix timestamps throughout (via `time.time()`)
- Removed …
=> Fix UploadManager timing synchronization between parent and child processes

RMS/Logger.py
Address issue #702 by removing QueueListener and implementing a single-consumer loop.
=> Fix async logger to preserve FIFO message order by removing QueueListener
